[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0x0f1419"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xC9CBFF"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0x0f1419"
yellow = "0xFAE3B0"

[colors.primary]
background = "0xeff1f5"
foreground = "0x0f1419"
