
# Paths 
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"
export PATH=/opt/homebrew/bin:$PATH

# Path to oh-my-zsh installation.
export ZSH="/Users/ckg/.oh-my-zsh"


# User Defined Paths
export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.8.1-src.zip
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin$PATH"
export PATH=$PATH:/usr/local/node/bin
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"



# ZSH THEME 
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell" #default for omz
#ZSH_THEME="duellj" #nice Theme, uses a lot of lines (see- https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#duellj)
ZSH_THEME="wizbang" #CKG Version of robbyrussell (save it in /Users/ckg-files/.oh-my-zsh/custom/themes)
#source "/opt/homebrew/opt/spaceship/spaceship.zsh" #alt to run the spaceship theme



# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# ZSH Plug-Ins 
# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git 
    # zsh-autosuggestions  #really not good
    zsh-syntax-highlighting
)




####---- CKG's Configs ----####
source $ZSH/oh-my-zsh.sh
source ~/.zsh_aliases 


# Set vim Mode for zsh
bindkey -v # insert mode comes default, hit escape to use the magic

# Set Up/Down Arrow to Traverse Command History (not default for zsh on all systems)
# taken from- https://superuser.com/questions/585003/searching-through-history-with-up-and-down-arrow-in-zsh
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "$key[Up]" up-line-or-beginning-search # Up
bindkey "$key[Down]" down-line-or-beginning-search # Down


# Specify the Language Environment
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi


## aliases (specific to MacOS)
# Light and Dark mode toggles for alacritty
# edit the alacritty config in-place to change the colors --> the extra '' after -i in sed is specific to MacOS
alias lm="sed -i ''  's/catppucin-dark.yml/catppucin-light.yml/' ~/.config/alacritty/alacritty.yml"
alias dm="sed -i ''  's/catppucin-light.yml/catppucin-dark.yml/' ~/.config/alacritty/alacritty.yml"

# things3 -- make use of their URL Wizard- https://culturedcode.com/things/support/articles/2803573/
alias tm="open 'things:///add?title=MEETING%20--%20$(date +'%Y-%m-%d')&notes=%23%20Information%0A%0A%23%20Notes%0A-%20%0A%0A&when=today&list=Notes'"



# Ruby
# stuff for my jeykll site, goodness gracious Ruby can be a pain
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.4


## application 
# Launch Docker in the Background -- a convenience on MacOS
if ! pgrep -f Docker > /dev/null; then
  open --background -a Docker
  while ! docker system info > /dev/null 2>&1; do sleep 1; done
fi




